### ISSUE TITLE
Some text are cut off

### ISSUE THREAD

**Issue by gscdev** [elimu-ai/vitabu#22]
Some texts are cut off and do not have scroll
![Screenshot_2020-10-27-00-07-42-504](https://user-images.githubusercontent.com/8291318/97238334-71dc1680-17e9-11eb-8bef-6a7ed5b66692.jpg)

**Comment by nya-elimuai** [comment]
Relates to #27

**Comment by nya-elimuai** [comment]
Relates to #35
