### ISSUE TITLE
Wrong underlined texts

### ISSUE THREAD

**Issue by gscdev** [elimu-ai/vitabu#23]
Some underlined texts do not correspond to words

**Comment by nya-elimuai** [comment]
Relates to #28

**Comment by nya-elimuai** [comment]
This bug might have something to do with `null` in a chapter's list of words: http://fil.test.elimu.ai/rest/v2/content/storybooks

```
		"storyBookParagraphs": [{
			"originalText": "Huli na si Chiu sa kanyang klase. Ngunit hindi niya makita ang kaniyang kulay pulang baunang bote.",
			"sortOrder": 0,
			"words": [null, {
				"id": 3
			}, {
				"id": 6
			}, null, {
				"id": 4
			}, {
				"id": 192
			}, null, {
				"id": 152
			}, {
				"id": 13
			}, {
				"id": 179
			}, {
				"id": 106
			}, {
				"id": 1
			}, {
				"id": 145
			}, {
				"id": 367
			}, {
				"id": 412
			}],
			"id": 393
		}]
```

**Comment by nya-elimuai** [comment]
![device-2020-12-16-212324](https://user-images.githubusercontent.com/15718174/102402486-7fde3480-3fed-11eb-9c3a-bcaba21d5962.png)

**Comment by gscdev** [comment]
![image](https://user-images.githubusercontent.com/8291318/107865288-194a8b00-6e65-11eb-8c9d-d4cc4d85ef82.png)

**Comment by nya-elimuai** [comment]
@gscdev This is amazing! Thank you very much for implementing this bug fix 🙂
