### ISSUE TITLE
Use different StoryBook font-size and letter-spacing per ReadingLevel

### ISSUE THREAD

**Issue by gscdev** [elimu-ai/vitabu#35]
Gradually reduce:
- [x] Font-size
- [x] Letter-spacing
- [x] Word-spacing

---

Relates to #26

**Comment by gscdev** [comment]
Related to #26

**Comment by nya-elimuai** [comment]
Depends on https://github.com/elimu-ai/webapp/issues/1086

**Comment by nya-elimuai** [comment]
Depends on #26
